#ifndef BINDLESSGLOBALDEF_SHARED_H
#define BINDLESSGLOBALDEF_SHARED_H
#define MAX_BUFFER_BINDLESS 512
#define BINDLESS_SET_IDX 0
#define BUFFER_BINDLESS_ARRAY_BINDING_IDX		0
#define UAV_IMAGE_BINDLESS_ARRAY_BINDING_IDX	1
#define SAMPLER_BINDLESS_ARRAY_BINDING_IDX		2
#define TEXTURE_BINDLESS_ARRAY_BINDING_IDX		3

#define MAX_TEXTURE_BINDLESS	  4096
#define MAX_STORAGEIMAGE_BINDLESS 512
#define MAX_SAMPLER_BINDLESS  128

#endif
